### ISSUE TITLE
Question: Do you develop mobile first & then tablet or mobile & tablet side by side ❓

### ISSUE THREAD

**Issue by deadcoder0904** [nirsky/react-native-size-matters#3]
I am gonna try my 1st project with React Native for Tablet using this awesome library. So I thought its better to ask you who has actually developed rather than posting on StackOverflow. Sorry for the issue though. 

So should I develop side by side for iOS & Android Tablets with ~5 inch Mobile or first all mobile then convert everything to Tablets. Also, how do you manage to keep iPad & iPhone open at the same time because when I open iPad, iPhone shuts down.

**Comment by nirsky** [comment]
@deadcoder0904 I personally like to complete the design first on a mobile phone and then start applying the scaling utils while running on tablet.
Since the sizes were created for mobile phone first you can rest assure your mobile design will hardly change after applying the utils, and work on the tablet without worrying.

**Comment by deadcoder0904** [comment]
Cool thanks 👍
