### ISSUE TITLE
[feature request] Add orientation change listener

### ISSUE THREAD

**Issue by karlmarxlopez** [nirsky/react-native-size-matters#30]
Hi, please add a utility or a container component to recalculate the dimensions when the device orientation change.

**Comment by nirsky** [comment]
Hey @karlmarxlopez, not sure how will this help?
StyleSheets are static, meaning changing the formulas won't make a difference in the already calculated sizes.
I also prefer they would stay static when using this lib due to performance.

If you'd like to use different styles for different orientation I suggest you implement your own listener and make your StyleSheets dynamic (create it inside the render).
Though I must say, a good design should handle both landscape and portrait with the same styles (using flex, etc..).
